import type { InstrumentListing, ListedPlatform } from "./prices";

export const REGISTRY_PLATFORMS: readonly ListedPlatform[] = [
  {
    slug: "wallgold",
    name_fa: "وال‌گلد",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Wallgold",
    website_url: "https://wallgold.ir",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "talasea",
    name_fa: "طلاسی",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Talasea",
    website_url: "https://talasea.ir",
    legal_entity: "شرکت توسعه راهکار الوند ارسباران",
    founded_year_jalali: null,
    delivery_note_fa: "تحویل فیزیکی با اجرت ساخت (نرخ اعلام عمومی نشده)",
  },
  {
    slug: "milli",
    name_fa: "میلی",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Milli",
    website_url: "https://milli.gold",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: "کارمزد تحویل فیزیکی ۳٪",
  },
  {
    slug: "goldika",
    name_fa: "گلدیکا",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Goldika",
    website_url: "https://goldika.ir",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "technogold",
    name_fa: "تکنوگلد",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Technogold",
    website_url: "https://technogold.gold",
    legal_entity: "بازوی فینتک هلدینگ تکنولایف",
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "tlyn",
    name_fa: "طلاین",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Tlyn",
    website_url: "https://taline.ir",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "ecogold",
    name_fa: "اکوگلد",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Ecogold",
    website_url: "https://ecogold.ir",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "zarafza",
    name_fa: "زرافزا",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Zarafza",
    website_url: "https://zarafza.com",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "baazar",
    name_fa: "بازر",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Baazar",
    website_url: "https://baazar.ir",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "daric",
    name_fa: "داریک",
    data_policy: "ALLOWED",
    market_model: "ORDER_BOOK",
    name_en: "Daric",
    website_url: "https://daric.gold",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "melligold",
    name_fa: "ملی‌گلد",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Melligold",
    website_url: "https://melligold.com",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "digikala",
    name_fa: "دیجی‌کالا",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Digikala",
    website_url: "https://www.digikala.com/wealth/",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa:
      "تحویل فیزیکی طلا از ۵٫۴ گرم؛ کارمزد ضرب و تحویل ۴۰۰ میلی‌گرم به‌ازای هر شمش ۵ گرمی (عملاً حدود ۸٪)",
  },
  {
    slug: "hamrahgold",
    name_fa: "همراه‌گلد",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Hamrahgold",
    website_url: "https://pwa.hamrahgold.com",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
  {
    slug: "invi",
    name_fa: "اینوی",
    data_policy: "ALLOWED",
    market_model: "OTC",
    name_en: "Invi",
    website_url: "https://invi.ir",
    legal_entity: null,
    founded_year_jalali: null,
    delivery_note_fa: null,
  },
];

/**
 * ⚠️ This list is only a **floor**: if the live `tablo:instruments` payload
 * is available, it takes precedence — so opening the gate for an asset in
 * the collector still takes effect without a web deploy.
 */
export const REGISTRY_INSTRUMENTS: readonly InstrumentListing[] = [
  {
    slug: "tala-18",
    instrument: "GOLD_18K",
    name_fa: "طلای ۱۸ عیار",
    unit_fa: "گرم",
    purity: "750",
    currency: "TOMAN",
    supporting_platform_slugs: [
      "wallgold",
      "talasea",
      "milli",
      "goldika",
      "technogold",
      "tlyn",
      "ecogold",
      "zarafza",
      "baazar",
      "daric",
      "melligold",
      "digikala",
      "hamrahgold",
      "invi",
    ],
    published: true,
  },
  {
    slug: "abshode",
    instrument: "ABSHODE_MITHQAL",
    name_fa: "طلای آب‌شده (مظنه)",
    unit_fa: "مثقال",
    purity: null,
    currency: "TOMAN",
    supporting_platform_slugs: [],
    published: false,
  },
  {
    slug: "noghre",
    instrument: "SILVER_990",
    name_fa: "نقره‌ی ۹۹۰",
    unit_fa: "گرم",
    purity: "990",
    currency: "TOMAN",
    supporting_platform_slugs: [],
    published: false,
  },
  {
    slug: "ons-jahani",
    instrument: "XAU",
    name_fa: "انس جهانی طلا",
    unit_fa: "اونس",
    purity: null,
    currency: "USD",
    supporting_platform_slugs: [],
    published: false,
  },
];
