/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AbzarhaRouteImport } from './routes/abzarha'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MazaneChistRouteImport } from './routes/mazane-chist'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MohasebeForushTalaRouteImport } from './routes/mohasebe-forush-tala'
import { Route as MohasebeTalaRouteImport } from './routes/mohasebe-tala'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SekehRouteImport } from './routes/sekeh'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminClicksRouteImport } from './routes/admin/clicks'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPlatformsRouteImport } from './routes/admin/platforms'
import { Route as ApiAdminCalcEventsRouteImport } from './routes/api/admin-calc-events'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin-login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin-logout'
import { Route as ApiAdminPlatformSettingsRouteImport } from './routes/api/admin-platform-settings'
import { Route as ApiAdminPostsRouteImport } from './routes/api/admin-posts'
import { Route as ApiAdminReferralClicksRouteImport } from './routes/api/admin-referral-clicks'
import { Route as ApiCalcEventRouteImport } from './routes/api/calc-event'
import { Route as ApiPostViewRouteImport } from './routes/api/post-view'
import { Route as ApiPricesRouteImport } from './routes/api/prices'
import { Route as ApiRevalidateBlogRouteImport } from './routes/api/revalidate-blog'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as GoSlugRouteImport } from './routes/go/$slug'
import { Route as OgKeyRouteImport } from './routes/og/$key'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminPostsSlugRouteImport } from './routes/admin/posts/$slug'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts/new'
import { Route as ApiAdminPostsSlugRouteImport } from './routes/api/admin-posts.$slug'
import { Route as ApiAdminPostsSlugImageRouteImport } from './routes/api/admin-posts.$slug.image'
import { Route as ApiAdminPostsSlugPublishRouteImport } from './routes/api/admin-posts.$slug.publish'
import { Route as ApiAdminPostsSlugRetractRouteImport } from './routes/api/admin-posts.$slug.retract'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AbzarhaRoute = AbzarhaRouteImport.update({
  id: '/abzarha',
  path: '/abzarha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MazaneChistRoute = MazaneChistRouteImport.update({
  id: '/mazane-chist',
  path: '/mazane-chist',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MohasebeForushTalaRoute = MohasebeForushTalaRouteImport.update({
  id: '/mohasebe-forush-tala',
  path: '/mohasebe-forush-tala',
  getParentRoute: () => rootRouteImport,
} as any)
const MohasebeTalaRoute = MohasebeTalaRouteImport.update({
  id: '/mohasebe-tala',
  path: '/mohasebe-tala',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SekehRoute = SekehRouteImport.update({
  id: '/sekeh',
  path: '/sekeh',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClicksRoute = AdminClicksRouteImport.update({
  id: '/clicks',
  path: '/clicks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlatformsRoute = AdminPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAdminCalcEventsRoute = ApiAdminCalcEventsRouteImport.update({
  id: '/api/admin-calc-events',
  path: '/api/admin-calc-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin-login',
  path: '/api/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin-logout',
  path: '/api/admin-logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlatformSettingsRoute =
  ApiAdminPlatformSettingsRouteImport.update({
    id: '/api/admin-platform-settings',
    path: '/api/admin-platform-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPostsRoute = ApiAdminPostsRouteImport.update({
  id: '/api/admin-posts',
  path: '/api/admin-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReferralClicksRoute = ApiAdminReferralClicksRouteImport.update({
  id: '/api/admin-referral-clicks',
  path: '/api/admin-referral-clicks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalcEventRoute = ApiCalcEventRouteImport.update({
  id: '/api/calc-event',
  path: '/api/calc-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostViewRoute = ApiPostViewRouteImport.update({
  id: '/api/post-view',
  path: '/api/post-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesRoute = ApiPricesRouteImport.update({
  id: '/api/prices',
  path: '/api/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateBlogRoute = ApiRevalidateBlogRouteImport.update({
  id: '/api/revalidate-blog',
  path: '/api/revalidate-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgKeyRoute = OgKeyRouteImport.update({
  id: '/og/$key',
  path: '/og/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsSlugRoute = AdminPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAdminPostsSlugRoute = ApiAdminPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiAdminPostsRoute,
} as any)
const ApiAdminPostsSlugImageRoute = ApiAdminPostsSlugImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiAdminPostsSlugRoute,
} as any)
const ApiAdminPostsSlugPublishRoute =
  ApiAdminPostsSlugPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiAdminPostsSlugRoute,
  } as any)
const ApiAdminPostsSlugRetractRoute =
  ApiAdminPostsSlugRetractRouteImport.update({
    id: '/retract',
    path: '/retract',
    getParentRoute: () => ApiAdminPostsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/abzarha': typeof AbzarhaRoute
  '/mazane-chist': typeof MazaneChistRoute
  '/methodology': typeof MethodologyRoute
  '/mohasebe-forush-tala': typeof MohasebeForushTalaRoute
  '/mohasebe-tala': typeof MohasebeTalaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sekeh': typeof SekehRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/clicks': typeof AdminClicksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/platforms': typeof AdminPlatformsRoute
  '/api/admin-calc-events': typeof ApiAdminCalcEventsRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-platform-settings': typeof ApiAdminPlatformSettingsRoute
  '/api/admin-posts': typeof ApiAdminPostsRouteWithChildren
  '/api/admin-referral-clicks': typeof ApiAdminReferralClicksRoute
  '/api/calc-event': typeof ApiCalcEventRoute
  '/api/post-view': typeof ApiPostViewRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/revalidate-blog': typeof ApiRevalidateBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/og/$key': typeof OgKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/admin-posts/$slug': typeof ApiAdminPostsSlugRouteWithChildren
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/api/admin-posts/$slug/image': typeof ApiAdminPostsSlugImageRoute
  '/api/admin-posts/$slug/publish': typeof ApiAdminPostsSlugPublishRoute
  '/api/admin-posts/$slug/retract': typeof ApiAdminPostsSlugRetractRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/abzarha': typeof AbzarhaRoute
  '/mazane-chist': typeof MazaneChistRoute
  '/methodology': typeof MethodologyRoute
  '/mohasebe-forush-tala': typeof MohasebeForushTalaRoute
  '/mohasebe-tala': typeof MohasebeTalaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sekeh': typeof SekehRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/clicks': typeof AdminClicksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/platforms': typeof AdminPlatformsRoute
  '/api/admin-calc-events': typeof ApiAdminCalcEventsRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-platform-settings': typeof ApiAdminPlatformSettingsRoute
  '/api/admin-posts': typeof ApiAdminPostsRouteWithChildren
  '/api/admin-referral-clicks': typeof ApiAdminReferralClicksRoute
  '/api/calc-event': typeof ApiCalcEventRoute
  '/api/post-view': typeof ApiPostViewRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/revalidate-blog': typeof ApiRevalidateBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/og/$key': typeof OgKeyRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/admin-posts/$slug': typeof ApiAdminPostsSlugRouteWithChildren
  '/admin/posts': typeof AdminPostsIndexRoute
  '/api/admin-posts/$slug/image': typeof ApiAdminPostsSlugImageRoute
  '/api/admin-posts/$slug/publish': typeof ApiAdminPostsSlugPublishRoute
  '/api/admin-posts/$slug/retract': typeof ApiAdminPostsSlugRetractRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/abzarha': typeof AbzarhaRoute
  '/mazane-chist': typeof MazaneChistRoute
  '/methodology': typeof MethodologyRoute
  '/mohasebe-forush-tala': typeof MohasebeForushTalaRoute
  '/mohasebe-tala': typeof MohasebeTalaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sekeh': typeof SekehRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/clicks': typeof AdminClicksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/platforms': typeof AdminPlatformsRoute
  '/api/admin-calc-events': typeof ApiAdminCalcEventsRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-platform-settings': typeof ApiAdminPlatformSettingsRoute
  '/api/admin-posts': typeof ApiAdminPostsRouteWithChildren
  '/api/admin-referral-clicks': typeof ApiAdminReferralClicksRoute
  '/api/calc-event': typeof ApiCalcEventRoute
  '/api/post-view': typeof ApiPostViewRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/revalidate-blog': typeof ApiRevalidateBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/og/$key': typeof OgKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/admin-posts/$slug': typeof ApiAdminPostsSlugRouteWithChildren
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/api/admin-posts/$slug/image': typeof ApiAdminPostsSlugImageRoute
  '/api/admin-posts/$slug/publish': typeof ApiAdminPostsSlugPublishRoute
  '/api/admin-posts/$slug/retract': typeof ApiAdminPostsSlugRetractRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$slug'
    | '/about'
    | '/abzarha'
    | '/mazane-chist'
    | '/methodology'
    | '/mohasebe-forush-tala'
    | '/mohasebe-tala'
    | '/robots.txt'
    | '/sekeh'
    | '/sitemap.xml'
    | '/admin/clicks'
    | '/admin/login'
    | '/admin/platforms'
    | '/api/admin-calc-events'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-platform-settings'
    | '/api/admin-posts'
    | '/api/admin-referral-clicks'
    | '/api/calc-event'
    | '/api/post-view'
    | '/api/prices'
    | '/api/revalidate-blog'
    | '/blog/$slug'
    | '/go/$slug'
    | '/og/$key'
    | '/admin/'
    | '/blog/'
    | '/admin/posts/$slug'
    | '/admin/posts/new'
    | '/api/admin-posts/$slug'
    | '/admin/posts/'
    | '/api/admin-posts/$slug/image'
    | '/api/admin-posts/$slug/publish'
    | '/api/admin-posts/$slug/retract'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/abzarha'
    | '/mazane-chist'
    | '/methodology'
    | '/mohasebe-forush-tala'
    | '/mohasebe-tala'
    | '/robots.txt'
    | '/sekeh'
    | '/sitemap.xml'
    | '/admin/clicks'
    | '/admin/login'
    | '/admin/platforms'
    | '/api/admin-calc-events'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-platform-settings'
    | '/api/admin-posts'
    | '/api/admin-referral-clicks'
    | '/api/calc-event'
    | '/api/post-view'
    | '/api/prices'
    | '/api/revalidate-blog'
    | '/blog/$slug'
    | '/go/$slug'
    | '/og/$key'
    | '/admin'
    | '/blog'
    | '/admin/posts/$slug'
    | '/admin/posts/new'
    | '/api/admin-posts/$slug'
    | '/admin/posts'
    | '/api/admin-posts/$slug/image'
    | '/api/admin-posts/$slug/publish'
    | '/api/admin-posts/$slug/retract'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$slug'
    | '/about'
    | '/abzarha'
    | '/mazane-chist'
    | '/methodology'
    | '/mohasebe-forush-tala'
    | '/mohasebe-tala'
    | '/robots.txt'
    | '/sekeh'
    | '/sitemap.xml'
    | '/admin/clicks'
    | '/admin/login'
    | '/admin/platforms'
    | '/api/admin-calc-events'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-platform-settings'
    | '/api/admin-posts'
    | '/api/admin-referral-clicks'
    | '/api/calc-event'
    | '/api/post-view'
    | '/api/prices'
    | '/api/revalidate-blog'
    | '/blog/$slug'
    | '/go/$slug'
    | '/og/$key'
    | '/admin/'
    | '/blog/'
    | '/admin/posts/$slug'
    | '/admin/posts/new'
    | '/api/admin-posts/$slug'
    | '/admin/posts/'
    | '/api/admin-posts/$slug/image'
    | '/api/admin-posts/$slug/publish'
    | '/api/admin-posts/$slug/retract'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AbzarhaRoute: typeof AbzarhaRoute
  MazaneChistRoute: typeof MazaneChistRoute
  MethodologyRoute: typeof MethodologyRoute
  MohasebeForushTalaRoute: typeof MohasebeForushTalaRoute
  MohasebeTalaRoute: typeof MohasebeTalaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SekehRoute: typeof SekehRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdminCalcEventsRoute: typeof ApiAdminCalcEventsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminPlatformSettingsRoute: typeof ApiAdminPlatformSettingsRoute
  ApiAdminPostsRoute: typeof ApiAdminPostsRouteWithChildren
  ApiAdminReferralClicksRoute: typeof ApiAdminReferralClicksRoute
  ApiCalcEventRoute: typeof ApiCalcEventRoute
  ApiPostViewRoute: typeof ApiPostViewRoute
  ApiPricesRoute: typeof ApiPricesRoute
  ApiRevalidateBlogRoute: typeof ApiRevalidateBlogRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  OgKeyRoute: typeof OgKeyRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abzarha': {
      id: '/abzarha'
      path: '/abzarha'
      fullPath: '/abzarha'
      preLoaderRoute: typeof AbzarhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mazane-chist': {
      id: '/mazane-chist'
      path: '/mazane-chist'
      fullPath: '/mazane-chist'
      preLoaderRoute: typeof MazaneChistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mohasebe-forush-tala': {
      id: '/mohasebe-forush-tala'
      path: '/mohasebe-forush-tala'
      fullPath: '/mohasebe-forush-tala'
      preLoaderRoute: typeof MohasebeForushTalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mohasebe-tala': {
      id: '/mohasebe-tala'
      path: '/mohasebe-tala'
      fullPath: '/mohasebe-tala'
      preLoaderRoute: typeof MohasebeTalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sekeh': {
      id: '/sekeh'
      path: '/sekeh'
      fullPath: '/sekeh'
      preLoaderRoute: typeof SekehRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clicks': {
      id: '/admin/clicks'
      path: '/clicks'
      fullPath: '/admin/clicks'
      preLoaderRoute: typeof AdminClicksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/platforms': {
      id: '/admin/platforms'
      path: '/platforms'
      fullPath: '/admin/platforms'
      preLoaderRoute: typeof AdminPlatformsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/admin-calc-events': {
      id: '/api/admin-calc-events'
      path: '/api/admin-calc-events'
      fullPath: '/api/admin-calc-events'
      preLoaderRoute: typeof ApiAdminCalcEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-login': {
      id: '/api/admin-login'
      path: '/api/admin-login'
      fullPath: '/api/admin-login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-logout': {
      id: '/api/admin-logout'
      path: '/api/admin-logout'
      fullPath: '/api/admin-logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-platform-settings': {
      id: '/api/admin-platform-settings'
      path: '/api/admin-platform-settings'
      fullPath: '/api/admin-platform-settings'
      preLoaderRoute: typeof ApiAdminPlatformSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-posts': {
      id: '/api/admin-posts'
      path: '/api/admin-posts'
      fullPath: '/api/admin-posts'
      preLoaderRoute: typeof ApiAdminPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-referral-clicks': {
      id: '/api/admin-referral-clicks'
      path: '/api/admin-referral-clicks'
      fullPath: '/api/admin-referral-clicks'
      preLoaderRoute: typeof ApiAdminReferralClicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calc-event': {
      id: '/api/calc-event'
      path: '/api/calc-event'
      fullPath: '/api/calc-event'
      preLoaderRoute: typeof ApiCalcEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/post-view': {
      id: '/api/post-view'
      path: '/api/post-view'
      fullPath: '/api/post-view'
      preLoaderRoute: typeof ApiPostViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices': {
      id: '/api/prices'
      path: '/api/prices'
      fullPath: '/api/prices'
      preLoaderRoute: typeof ApiPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate-blog': {
      id: '/api/revalidate-blog'
      path: '/api/revalidate-blog'
      fullPath: '/api/revalidate-blog'
      preLoaderRoute: typeof ApiRevalidateBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$key': {
      id: '/og/$key'
      path: '/og/$key'
      fullPath: '/og/$key'
      preLoaderRoute: typeof OgKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$slug': {
      id: '/admin/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/admin/posts/$slug'
      preLoaderRoute: typeof AdminPostsSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/admin-posts/$slug': {
      id: '/api/admin-posts/$slug'
      path: '/$slug'
      fullPath: '/api/admin-posts/$slug'
      preLoaderRoute: typeof ApiAdminPostsSlugRouteImport
      parentRoute: typeof ApiAdminPostsRoute
    }
    '/api/admin-posts/$slug/image': {
      id: '/api/admin-posts/$slug/image'
      path: '/image'
      fullPath: '/api/admin-posts/$slug/image'
      preLoaderRoute: typeof ApiAdminPostsSlugImageRouteImport
      parentRoute: typeof ApiAdminPostsSlugRoute
    }
    '/api/admin-posts/$slug/publish': {
      id: '/api/admin-posts/$slug/publish'
      path: '/publish'
      fullPath: '/api/admin-posts/$slug/publish'
      preLoaderRoute: typeof ApiAdminPostsSlugPublishRouteImport
      parentRoute: typeof ApiAdminPostsSlugRoute
    }
    '/api/admin-posts/$slug/retract': {
      id: '/api/admin-posts/$slug/retract'
      path: '/retract'
      fullPath: '/api/admin-posts/$slug/retract'
      preLoaderRoute: typeof ApiAdminPostsSlugRetractRouteImport
      parentRoute: typeof ApiAdminPostsSlugRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminClicksRoute: typeof AdminClicksRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPlatformsRoute: typeof AdminPlatformsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsSlugRoute: typeof AdminPostsSlugRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminClicksRoute: AdminClicksRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPlatformsRoute: AdminPlatformsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsSlugRoute: AdminPostsSlugRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApiAdminPostsSlugRouteChildren {
  ApiAdminPostsSlugImageRoute: typeof ApiAdminPostsSlugImageRoute
  ApiAdminPostsSlugPublishRoute: typeof ApiAdminPostsSlugPublishRoute
  ApiAdminPostsSlugRetractRoute: typeof ApiAdminPostsSlugRetractRoute
}

const ApiAdminPostsSlugRouteChildren: ApiAdminPostsSlugRouteChildren = {
  ApiAdminPostsSlugImageRoute: ApiAdminPostsSlugImageRoute,
  ApiAdminPostsSlugPublishRoute: ApiAdminPostsSlugPublishRoute,
  ApiAdminPostsSlugRetractRoute: ApiAdminPostsSlugRetractRoute,
}

const ApiAdminPostsSlugRouteWithChildren =
  ApiAdminPostsSlugRoute._addFileChildren(ApiAdminPostsSlugRouteChildren)

interface ApiAdminPostsRouteChildren {
  ApiAdminPostsSlugRoute: typeof ApiAdminPostsSlugRouteWithChildren
}

const ApiAdminPostsRouteChildren: ApiAdminPostsRouteChildren = {
  ApiAdminPostsSlugRoute: ApiAdminPostsSlugRouteWithChildren,
}

const ApiAdminPostsRouteWithChildren = ApiAdminPostsRoute._addFileChildren(
  ApiAdminPostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AbzarhaRoute: AbzarhaRoute,
  MazaneChistRoute: MazaneChistRoute,
  MethodologyRoute: MethodologyRoute,
  MohasebeForushTalaRoute: MohasebeForushTalaRoute,
  MohasebeTalaRoute: MohasebeTalaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SekehRoute: SekehRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdminCalcEventsRoute: ApiAdminCalcEventsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminPlatformSettingsRoute: ApiAdminPlatformSettingsRoute,
  ApiAdminPostsRoute: ApiAdminPostsRouteWithChildren,
  ApiAdminReferralClicksRoute: ApiAdminReferralClicksRoute,
  ApiCalcEventRoute: ApiCalcEventRoute,
  ApiPostViewRoute: ApiPostViewRoute,
  ApiPricesRoute: ApiPricesRoute,
  ApiRevalidateBlogRoute: ApiRevalidateBlogRoute,
  BlogSlugRoute: BlogSlugRoute,
  GoSlugRoute: GoSlugRoute,
  OgKeyRoute: OgKeyRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
