/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as DarbarePishnahadRouteImport } from './routes/darbare-pishnahad'
import { Route as MazaneChistRouteImport } from './routes/mazane-chist'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiPostViewRouteImport } from './routes/api/post-view'
import { Route as ApiPricesRouteImport } from './routes/api/prices'
import { Route as ApiRevalidateBlogRouteImport } from './routes/api/revalidate-blog'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as GoSlugRouteImport } from './routes/go/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DarbarePishnahadRoute = DarbarePishnahadRouteImport.update({
  id: '/darbare-pishnahad',
  path: '/darbare-pishnahad',
  getParentRoute: () => rootRouteImport,
} as any)
const MazaneChistRoute = MazaneChistRouteImport.update({
  id: '/mazane-chist',
  path: '/mazane-chist',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostViewRoute = ApiPostViewRouteImport.update({
  id: '/api/post-view',
  path: '/api/post-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesRoute = ApiPricesRouteImport.update({
  id: '/api/prices',
  path: '/api/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateBlogRoute = ApiRevalidateBlogRouteImport.update({
  id: '/api/revalidate-blog',
  path: '/api/revalidate-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/darbare-pishnahad': typeof DarbarePishnahadRoute
  '/mazane-chist': typeof MazaneChistRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/post-view': typeof ApiPostViewRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/revalidate-blog': typeof ApiRevalidateBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/darbare-pishnahad': typeof DarbarePishnahadRoute
  '/mazane-chist': typeof MazaneChistRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/post-view': typeof ApiPostViewRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/revalidate-blog': typeof ApiRevalidateBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/darbare-pishnahad': typeof DarbarePishnahadRoute
  '/mazane-chist': typeof MazaneChistRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/post-view': typeof ApiPostViewRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/revalidate-blog': typeof ApiRevalidateBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/darbare-pishnahad'
    | '/mazane-chist'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/post-view'
    | '/api/prices'
    | '/api/revalidate-blog'
    | '/blog/$slug'
    | '/go/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/darbare-pishnahad'
    | '/mazane-chist'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/post-view'
    | '/api/prices'
    | '/api/revalidate-blog'
    | '/blog/$slug'
    | '/go/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/darbare-pishnahad'
    | '/mazane-chist'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/post-view'
    | '/api/prices'
    | '/api/revalidate-blog'
    | '/blog/$slug'
    | '/go/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  DarbarePishnahadRoute: typeof DarbarePishnahadRoute
  MazaneChistRoute: typeof MazaneChistRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPostViewRoute: typeof ApiPostViewRoute
  ApiPricesRoute: typeof ApiPricesRoute
  ApiRevalidateBlogRoute: typeof ApiRevalidateBlogRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darbare-pishnahad': {
      id: '/darbare-pishnahad'
      path: '/darbare-pishnahad'
      fullPath: '/darbare-pishnahad'
      preLoaderRoute: typeof DarbarePishnahadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mazane-chist': {
      id: '/mazane-chist'
      path: '/mazane-chist'
      fullPath: '/mazane-chist'
      preLoaderRoute: typeof MazaneChistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/post-view': {
      id: '/api/post-view'
      path: '/api/post-view'
      fullPath: '/api/post-view'
      preLoaderRoute: typeof ApiPostViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices': {
      id: '/api/prices'
      path: '/api/prices'
      fullPath: '/api/prices'
      preLoaderRoute: typeof ApiPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate-blog': {
      id: '/api/revalidate-blog'
      path: '/api/revalidate-blog'
      fullPath: '/api/revalidate-blog'
      preLoaderRoute: typeof ApiRevalidateBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  DarbarePishnahadRoute: DarbarePishnahadRoute,
  MazaneChistRoute: MazaneChistRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPostViewRoute: ApiPostViewRoute,
  ApiPricesRoute: ApiPricesRoute,
  ApiRevalidateBlogRoute: ApiRevalidateBlogRoute,
  BlogSlugRoute: BlogSlugRoute,
  GoSlugRoute: GoSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
